"""
Self-Authored Module Registry
=============================
Tracks provenance for all modules generated by the meta-agent.
Every self-authored module is reviewable, diffable, and revertible.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

REGISTRY_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "meta_registry.json"


class MetaRegistry:
    """Registry of self-authored modules with full provenance."""

    def __init__(self, path: Path = REGISTRY_PATH):
        self.path = path
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._entries: Dict[str, dict] = {}
        self._load()

    def _load(self):
        if self.path.exists():
            with open(self.path) as f:
                self._entries = json.load(f)

    def _save(self):
        with open(self.path, "w") as f:
            json.dump(self._entries, f, indent=2, default=str)

    def register(self, name: str, provenance: dict) -> bool:
        """
        Register a self-authored module.

        Args:
            name: Module name (e.g. "blog_seo")
            provenance: {prompt, model, timestamp, tests_passed, code_path, status}
        """
        self._entries[name] = {
            **provenance,
            "registered_at": datetime.now().isoformat(),
        }
        self._save()
        logger.info(f"Meta module registered: {name}")
        return True

    def get(self, name: str) -> Optional[dict]:
        return self._entries.get(name)

    def list_all(self) -> Dict[str, dict]:
        return self._entries.copy()

    def update_status(self, name: str, status: str):
        """Update module status: draft → testing → approved | rejected."""
        if name in self._entries:
            self._entries[name]["status"] = status
            if status == "approved":
                self._entries[name]["approved_at"] = datetime.now().isoformat()
            self._save()

    def delete(self, name: str) -> bool:
        if name in self._entries:
            del self._entries[name]
            self._save()
            return True
        return False
