"""
Code Generator
==============
Automatic code generation for test scripts.

Author: CureMD BA QA Team
Version: 1.0.0
"""

import logging
from enum import Enum
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field


logger = logging.getLogger("coder.generation")


# ============================================================================
# ENUMS AND DATA CLASSES
# ============================================================================

class Language(Enum):
    """Supported programming languages."""
    PYTHON = "python"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"
    JAVA = "java"
    CSHARP = "csharp"
    GO = "go"
    RUST = "rust"


@dataclass
class CodeTemplate:
    """Code template for a specific type of script."""
    name: str
    language: Language
    template: str
    description: str = ""
    variables: List[str] = field(default_factory=list)
    imports: List[str] = field(default_factory=list)


@dataclass
class GeneratedCode:
    """Generated code with metadata."""
    code: str
    language: Language
    filename: str
    template_used: str
    imports: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


# ============================================================================
# CODE TEMPLATES
# ============================================================================

PYTHON_PLAYWRIGHT_TEMPLATE = '''"""
{title}
Generated by CureMD QA Automation Suite
"""

import asyncio
import pytest
from playwright.async_api import async_playwright, Page, expect


class {class_name}:
    """Test class for {feature}."""
    
    def __init__(self):
        self.browser = None
        self.context = None
        self.page = None
    
    async def setup(self):
        """Setup browser and page."""
        self.playwright = await async_playwright().start()
        self.browser = await self.playwright.chromium.launch(headless={headless})
        self.context = await self.browser.new_context(viewport={{"width": 1920, "height": 1080}})
        self.page = await self.context.new_page()
    
    async def teardown(self):
        """Cleanup resources."""
        if self.browser:
            await self.browser.close()
        if self.playwright:
            await self.playwright.stop()
    
    {methods}


async def run_tests():
    """Run all tests."""
    test = {class_name}()
    try:
        await test.setup()
        # Run test methods
        {test_calls}
    finally:
        await test.teardown()


if __name__ == "__main__":
    asyncio.run(run_tests())
'''


PYTHON_SELENIUM_TEMPLATE = '''"""
{title}
Generated by CureMD QA Automation Suite
"""

import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class {class_name}:
    """Test class for {feature}."""
    
    def setup_method(self):
        """Setup driver."""
        options = webdriver.ChromeOptions()
        options.add_argument('--headless')
        self.driver = webdriver.Chrome(options=options)
        self.driver.implicitly_wait(10)
    
    def teardown_method(self):
        """Cleanup driver."""
        if self.driver:
            self.driver.quit()
    
    {methods}


if __name__ == "__main__":
    pytest.main([__file__, '-v'])
'''


JAVASCRIPT_PLAYWRIGHT_TEMPLATE = '''
/**
 * {title}
 * Generated by CureMD QA Automation Suite
 */

const {{ chromium }} = require('playwright');

class {class_name} {{
    constructor() {{
        this.browser = null;
        this.context = null;
        this.page = null;
    }}
    
    async setup() {{
        this.browser = await chromium.launch({{ headless: {headless} }});
        this.context = await this.browser.newContext();
        this.page = await this.context.newPage();
    }}
    
    async teardown() {{
        if (this.browser) {{
            await this.browser.close();
        }}
    }}
    
    {methods}
}}

async function runTests() {{
    const test = new {class_name}();
    try {{
        await test.setup();
        // Run test methods
        {test_calls}
    }} finally {{
        await test.teardown();
    }}
}}

module.exports = {{ {class_name}, runTests }};
'''


API_TEST_TEMPLATE = '''"""
{title}
Generated by CureMD QA Automation Suite
"""

import requests
import pytest


class {class_name}:
    """API test class for {feature}."""
    
    def __init__(self, base_url="{base_url}"):
        self.base_url = base_url
        self.session = requests.Session()
    
    {methods}


def test_api():
    """Run API tests."""
    test = {class_name}()
    {test_calls}


if __name__ == "__main__":
    pytest.main([__file__, '-v'])
'''


UNIT_TEST_TEMPLATE = '''"""
{title}
Generated by CureMD QA Automation Suite
"""

import pytest


class {class_name}:
    """Unit test class for {feature}."""
    
    {methods}


def test_all():
    """Run all tests."""
    test = {class_name}()
    {test_calls}


if __name__ == "__main__":
    pytest.main([__file__, '-v'])
'''


# ============================================================================
# CODE GENERATOR CLASS
# ============================================================================

class CodeGenerator:
    """
    Generates test code from specifications.
    
    Supports multiple languages and frameworks.
    """
    
    def __init__(self, language: Language = Language.PYTHON):
        self.language = language
        self.logger = logging.getLogger(f"coder.{language.value}")
        self._templates = self._load_templates()
    
    def _load_templates(self) -> Dict[str, str]:
        """Load code templates."""
        return {
            "playwright_python": PYTHON_PLAYWRIGHT_TEMPLATE,
            "selenium_python": PYTHON_SELENIUM_TEMPLATE,
            "playwright_js": JAVASCRIPT_PLAYWRIGHT_TEMPLATE,
            "api_python": API_TEST_TEMPLATE,
            "unit_python": UNIT_TEST_TEMPLATE,
        }
    
    def generate(
        self,
        name: str,
        feature: str,
        test_type: str = "ui",
        framework: str = "playwright",
        **kwargs
    ) -> GeneratedCode:
        """
        Generate test code.
        
        Args:
            name: Test class/module name
            feature: Feature being tested
            test_type: Type of test (ui, api, unit)
            framework: Framework to use (playwright, selenium)
            **kwargs: Additional parameters
            
        Returns:
            Generated code
        """
        self.logger.info(f"Generating {test_type} test for {feature}")
        
        # Determine template
        template_key = f"{framework}_{self.language.value}"
        if template_key not in self._templates:
            template_key = f"{test_type}_{self.language.value}"
        
        template = self._templates.get(template_key, UNIT_TEST_TEMPLATE)
        
        # Generate filename
        filename = f"test_{name.lower().replace(' ', '_')}.{self._get_extension()}"
        
        # Fill template
        class_name = self._to_pascal_case(name)
        code = template.format(
            title=f"{feature} - {test_type.upper()} Tests",
            class_name=class_name,
            feature=feature,
            headless=kwargs.get('headless', 'True'),
            base_url=kwargs.get('base_url', 'https://api.example.com'),
            methods=kwargs.get('methods', '    pass'),
            test_calls=kwargs.get('test_calls', ''),
            imports=kwargs.get('imports', [])
        )
        
        return GeneratedCode(
            code=code,
            language=self.language,
            filename=filename,
            template_used=template_key,
            imports=self._get_imports(test_type, framework),
            metadata={
                "feature": feature,
                "test_type": test_type,
                "framework": framework
            }
        )
    
    def generate_ui_test(
        self,
        name: str,
        feature: str,
        steps: List[Dict[str, Any]],
        framework: str = "playwright"
    ) -> GeneratedCode:
        """Generate UI test with steps."""
        methods = []
        test_calls = []
        
        for i, step in enumerate(steps):
            method_name = f"test_step_{i + 1}"
            method_code = self._generate_step_method(step, method_name)
            methods.append(method_code)
            test_calls.append(f"        await test.{method_name}()")
        
        return self.generate(
            name=name,
            feature=feature,
            test_type="ui",
            framework=framework,
            methods="\n\n".join(methods),
            test_calls="\n".join(test_calls)
        )
    
    def generate_api_test(
        self,
        name: str,
        endpoint: str,
        method: str,
        expected_status: int = 200
    ) -> GeneratedCode:
        """Generate API test."""
        method_name = f"test_{endpoint.replace('/', '_').strip('_')}"
        
        if self.language == Language.PYTHON:
            method_code = f'''
    def {method_name}(self):
        """Test {endpoint}."""
        response = self.session.{method}("{endpoint}")
        assert response.status_code == {expected_status}
'''
        else:
            method_code = f'''
    async {method_name}() {{
        const response = await this.page.request.{method}("{endpoint}");
        expect(response.status()).toBe({expected_status});
    }}
'''
        
        return self.generate(
            name=name,
            feature=f"API - {endpoint}",
            test_type="api",
            methods=method_code,
            test_calls=f"    test.{method_name}()",
            base_url="https://api.example.com"
        )
    
    def _generate_step_method(self, step: Dict, name: str) -> str:
        """Generate a method for a test step."""
        action = step.get("action", "navigate")
        selector = step.get("selector", "")
        value = step.get("value", "")
        
        if self.language == Language.PYTHON:
            if action == "navigate":
                return f'''
    async def {name}(self):
        """Navigate to {value}."""
        await self.page.goto("{value}")
'''
            elif action == "click":
                return f'''
    async def {name}(self):
        """Click element."""
        await self.page.click("{selector}")
'''
            elif action == "type":
                return f'''
    async def {name}(self):
        """Type text."""
        await self.page.fill("{selector}", "{value}")
'''
            elif action == "assert":
                return f'''
    async def {name}(self):
        """Assert element."""
        await expect(self.page.locator("{selector}")).to_be_visible()
'''
            else:
                return f'''
    async def {name}(self):
        """Execute action: {action}."""
        pass
'''
        else:
            # JavaScript
            if action == "navigate":
                return f'''
    async {name}() {{
        await this.page.goto("{value}");
    }}
'''
            elif action == "click":
                return f'''
    async {name}() {{
        await this.page.click("{selector}");
    }}
'''
            elif action == "type":
                return f'''
    async {name}() {{
        await this.page.fill("{selector}", "{value}");
    }}
'''
            else:
                return f'''
    async {name}() {{
        // {action}
    }}
'''
    
    def _get_imports(self, test_type: str, framework: str) -> List[str]:
        """Get import statements."""
        if self.language == Language.PYTHON:
            if test_type == "ui":
                if framework == "playwright":
                    return ["asyncio", "pytest", "playwright.async_api"]
                else:
                    return ["pytest", "selenium", "selenium.webdriver"]
            elif test_type == "api":
                return ["requests", "pytest"]
            else:
                return ["pytest"]
        else:
            if test_type == "ui":
                return ["playwright"]
            else:
                return []
    
    def _get_extension(self) -> str:
        """Get file extension for language."""
        extensions = {
            Language.PYTHON: "py",
            Language.JAVASCRIPT: "js",
            Language.TYPESCRIPT: "ts",
            Language.JAVA: "java",
            Language.CSHARP: "cs",
            Language.GO: "go",
            Language.RUST: "rs"
        }
        return extensions.get(self.language, "py")
    
    @staticmethod
    def _to_pascal_case(text: str) -> str:
        """Convert text to PascalCase."""
        return "".join(word.title().replace(" ", "") for word in text.split("_"))


# ============================================================================
# STANDALONE FUNCTION
# ============================================================================

def generate_test_script(
    name: str,
    feature: str,
    test_type: str = "ui",
    language: str = "python",
    **kwargs
) -> GeneratedCode:
    """
    Standalone function to generate test scripts.
    
    Args:
        name: Test name
        feature: Feature being tested
        test_type: Type of test
        language: Programming language
        **kwargs: Additional parameters
        
    Returns:
        Generated code
    """
    lang = Language(language.lower())
    generator = CodeGenerator(language=lang)
    return generator.generate(name, feature, test_type, **kwargs)


if __name__ == "__main__":
    # Test generation
    generator = CodeGenerator(Language.PYTHON)
    
    # UI test
    result = generator.generate_ui_test(
        name="Login Test",
        feature="User Authentication",
        steps=[
            {"action": "navigate", "value": "https://example.com/login"},
            {"action": "type", "selector": "#username", "value": "user@example.com"},
            {"action": "type", "selector": "#password", "value": "password123"},
            {"action": "click", "selector": "button[type='submit']"},
            {"action": "assert", "selector": ".welcome-message"}
        ]
    )
    
    print(f"Generated: {result.filename}")
    print(result.code)
    
    # API test
    result = generator.generate_api_test(
        name="Health Check",
        endpoint="/health",
        method="get",
        expected_status=200
    )
    
    print(f"\nGenerated: {result.filename}")
    print(result.code)